#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
hr=0
min=1
while [ $hr -le 12 ]
do
    echo "Hour: "$hr
    while [ $min -lt 60 ]
    do
        echo $min
	((min++))
    done
    ((min = 1))
    ((hr++))
done
